@chatservice_HostAddress = http://localhost:5109

### Get all messages for a user
GET {{chatservice_HostAddress}}/api/messages/user123
Accept: application/json

###

### Get conversation between two users
GET {{chatservice_HostAddress}}/api/messages/user123/user456
Accept: application/json

###

### Send a new message
POST {{chatservice_HostAddress}}/api/messages
Content-Type: application/json

{
  "senderId": "user123",
  "receiverId": "user456",
  "content": "Hello there!"
}
